DichVuMotCua/Models/thutuc.cs
namespace DichVuMotCua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("thutuc")]
    public partial class thutuc
    {
        public int id { get; set; }

        [StringLength(255)]
        public string name { get; set; }

        public int? nguoitao { get; set; }

        public int? nguoiduyet { get; set; }

        public int? loaithutuc { get; set; }

        public string ghichu { get; set; }

        public DateTime? ngaylay { get; set; }

        public int? tinhtrang { get; set; }

        public DateTime? ngaytao { get; set; }
    }
}

DichVuMotCua/Controllers/thutucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DichVuMotCua.Areas.Admin.Controllers;
using DichVuMotCua.Content;
using DichVuMotCua.Models;
using DocumentFormat.OpenXml.Packaging;
using Newtonsoft.Json;
namespace DichVuMotCua.Controllers
{
    public class thutucsController : BaseLoginController
    {
        private DBmodels db = new DBmodels();
        public thutucsController()
        {
            var khoas = db.khoas.ToList();
            List<SelectListItem> listItems = new List<SelectListItem>();
            foreach (var item in khoas)
            {
                listItems.Add(new SelectListItem
                {
                    Text = item.name.ToString(),
                    Value = item.name.ToString(),
                    Selected = true
                });
            }
            ViewBag.khoa = listItems;

        }

        
        

        // GET: thutucs
        public ActionResult Index()
        {
            var result = BaseLogin(db.thutucs.ToList());
            return result;
        }

        // GET: thutucs/Details/5
        public ActionResult Details(int? id, int idForm)
        {
            string data = "";
            if (idForm == Constants.XINTHOIHOC)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                thutuc thutuc = db.thutucs.Find(id);
                var hocphan = db.hocphans.Where(i => i.thutuc_id == thutuc.id).ToList();
                var chitietthutuc = db.chitietthutucs.Where(i => i.thutuc == thutuc.id).ToList();



                using (var reader = new StreamReader(Server.MapPath("/static/html/") + "MAUdangkytamdung.html"))
                {
                    string line = reader.ReadLine();
                    while (line != null)
                    {
                        data += line;
                        line = reader.ReadLine();
                    }
                }
                // thong tin sinh vien
                foreach (chitietthutuc item in chitietthutuc)
                {
                    data = data.Replace("DATAHOVATEN", ("Họ Và Tên").Equals(item.noidung) ? item.value : "DATAHOVATEN");
                    data = data.Replace("DATAMSV", ("Mã SV").Equals(item.noidung) ? item.value : "DATAMSV");
                    data = data.Replace("DATANGAYSINH", ("Ngày Sinh").Equals(item.noidung) ? item.value : "DATANGAYSINH");
                    data = data.Replace("DATALOP", ("Lớp").Equals(item.noidung) ? item.value : "DATALOP");
                    data = data.Replace("DATAKHOA", ("Khoa").Equals(item.noidung) ? item.value : "DATAKHOA");
                    data = data.Replace("DATAHOCKI", ("Học Kì Đã Học").Equals(item.noidung) ? item.value : "DATAHOCKI");
                    data = data.Replace("DATADVHTTIEUDE", ("ĐVHT").Equals(item.noidung) ? item.value : "DATADVHTTIEUDE");

                    data = data.Replace("DATANGAYNGHI", ("Ngày Nghỉ").Equals(item.noidung) ? item.value : "DATANGAYNGHI");
                    data = data.Replace("DATANGAYDIHOC", ("Ngày Đi Học").Equals(item.noidung) ? item.value : "DATANGAYDIHOC");
                    data = data.Replace("DATALYDO", ("Lý Do").Equals(item.noidung) ? item.value : "DATALYDO");
                }

                int stt = 0;
                data = data.Replace("DATAHP10", "");
                data = data.Replace("DATATHP10", "");
                data = data.Replace("DATADVHT10", "");
                data = data.Replace("DATANGAYHOCLAI10", "");
                foreach (hocphan item in hocphan)
                {
                    stt++;
                    data = data.Replace("DATAHP" + stt, item.mahocphan);
                    data = data.Replace("DATATHP" + stt, item.tenhocphan);
                    data = data.Replace("DATADVHT" + stt, item.soDVHT);
                    data = data.Replace("DATANGAYHOCLAI" + stt, item.thoigianhoclai.Year < 2000 ? "":item.thoigianhoclai.ToString("yyyy-MM-dd"));
                }

                for (int i = 0; i <= 10; i++)
                {
                    data = data.Replace("DATAHP" + i, "");
                    data = data.Replace("DATATHP" + i, "");
                    data = data.Replace("DATADVHT" + i, "");
                    data = data.Replace("DATANGAYHOCLAI" + i, "");
                }
            }
            else if (idForm == Constants.BAOLUUKETQUAHOCTAP)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                thutuc thutuc = db.thutucs.Find(id);
                var chitietthutuc = db.chitietthutucs.Where(i => i.thutuc == thutuc.id).ToList();



                using (var reader = new StreamReader(Server.MapPath("/static/html/") + "baoluuketquahoctap.html"))
                {
                    string line = reader.ReadLine();
                    while (line != null)
                    {
                        data += line;
                        line = reader.ReadLine();
                    }
                }
                // thong tin sinh vien
                foreach (chitietthutuc item in chitietthutuc)
                {
                    data = data.Replace("DATAKHOA", ("Khoa").Equals(item.noidung) ? item.value : "DATAKHOA");
                    data = data.Replace("DATAHOTEN", ("Họ Tên").Equals(item.noidung) ? item.value : "DATAHOTEN");
                    data = data.Replace("DATAMSV", ("Mã SV").Equals(item.noidung) ? item.value : "DATAMSV");
                    data = data.Replace("DATANGAYSINH", ("Ngày Sinh").Equals(item.noidung) ? item.value : "DATANGAYSINH");
                    data = data.Replace("DATANOISINH", ("Nơi Sinh").Equals(item.noidung) ? item.value : "DATANOISINH");
                    data = data.Replace("DATALOP", ("Lớp").Equals(item.noidung) ? item.value : "DATALOP");
                    data = data.Replace("DATATHUONGTRU", ("Thường Trú").Equals(item.noidung) ? item.value : "DATATHUONGTRU");

                    data = data.Replace("DATASDT", ("SĐT").Equals(item.noidung) ? item.value : "DATASDT");
                    data = data.Replace("DATAHK1", ("TBC Học Kỳ 1").Equals(item.noidung) ? item.value : "DATAHK1");
                    data = data.Replace("DATAHK2", ("TBC Học Kỳ 2").Equals(item.noidung) ? item.value : "DATAHK2");
                    data = data.Replace("DATAHK3", ("TBC Học Kỳ 3").Equals(item.noidung) ? item.value : "DATAHK3");
                    data = data.Replace("DATAHK4", ("TBC Học Kỳ 4").Equals(item.noidung) ? item.value : "DATAHK4");
                    data = data.Replace("DATAHK5", ("TBC Học Kỳ 5").Equals(item.noidung) ? item.value : "DATAHK5");
                    data = data.Replace("DATAHK6", ("TBC Học Kỳ 6").Equals(item.noidung) ? item.value : "DATAHK6");
                    data = data.Replace("DATABAOLUUTU", ("Bảo Lưu Từ").Equals(item.noidung) ? item.value : "DATABAOLUUTU");
                    data = data.Replace("DATABAOLUUDEN", ("Ngày Học Lại").Equals(item.noidung) ? item.value : "DATABAOLUUDEN");
                    data = data.Replace("DATALYDO", ("Lý Do").Equals(item.noidung) ? item.value : "DATALYDO");

                }
            }

            else if (idForm == Constants.BAOLUUKETQUATUYENSINH)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                thutuc thutuc = db.thutucs.Find(id);
                var chitietthutuc = db.chitietthutucs.Where(i => i.thutuc == thutuc.id).ToList();



                using (var reader = new StreamReader(Server.MapPath("/static/html/") + "baoluuketquatuyensinh.html"))
                {
                    string line = reader.ReadLine();
                    while (line != null)
                    {
                        data += line;
                        line = reader.ReadLine();
                    }
                }
                // thong tin sinh vien
                foreach (chitietthutuc item in chitietthutuc)
                {
                    data = data.Replace("DATAHOTEN", ("Họ Tên").Equals(item.noidung) ? item.value : "DATAHOTEN");
                    data = data.Replace("DATAMASV", ("Mã SV").Equals(item.noidung) ? item.value : "DATAMASV");
                    data = data.Replace("DATANGAYSINH", ("Năm Sinh").Equals(item.noidung) ? item.value : "DATANGAYSINH");
                    data = data.Replace("DATANOISINH", ("Nơi Sinh").Equals(item.noidung) ? item.value : "DATANOISINH");
                    data = data.Replace("DATASBD", ("Số Báo Danh").Equals(item.noidung) ? item.value : "DATASBD");
                    data = data.Replace("DATANAMTUYENSINH", ("Năm Thi Tuyển").Equals(item.noidung) ? item.value : "DATANAMTUYENSINH");
                    data = data.Replace("DATANGANH", ("Ngành Trúng Tuyển").Equals(item.noidung) ? item.value : "DATANGANH");
                    data = data.Replace("DATAMANGANH", ("Mã Ngành").Equals(item.noidung) ? item.value : "DATAMANGANH");

                    data = data.Replace("DATATONGDIEM", ("Tổng Điểm").Equals(item.noidung) ? item.value : "DATATONGDIEM");
                    data = data.Replace("DATABAOLUUDENNAM", ("Bảo Lưu Đến").Equals(item.noidung) ? item.value : "DATABAOLUUDENNAM");
                    data = data.Replace("DATALYDO", ("Lý Do").Equals(item.noidung) ? item.value : "DATALYDO");

                }
            }

            // chuyển điểm 

            else if (idForm == Constants.CHUYENDIEM)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                thutuc thutuc = db.thutucs.Find(id);

DichVuMotCua/Views/thutucs/CapGiayChungNhan.cshtml
@model DichVuMotCua.Models.thutuc

@{
    ViewBag.Title = "CapGiayChungNhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <body>
        @using (Html.BeginForm("CapGiayChungNhan",
             "thutucs",
             FormMethod.Post,
             new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2" for="tenthutuc">Tiêu Đề</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @if (ViewBag.chitietthutuc != null)
                {
                    for (int i = 0; i < ViewBag.chitietthutuc.Count; i++)
                    {
                        ViewBag.thongtinthutuc = "thutuc" + i;
                        ViewBag.thongtinthutucname = "thutucname" + i;
                        <div class="form-group">
                            <label class="control-label col-md-2" for="name">@ViewBag.chitietthutuc[i].name</label>
                            <div class="col-md-10">a
                                <input type="hidden" id="@ViewBag.thongtinthutucname" name="@ViewBag.thongtinthutucname" value="@ViewBag.chitietthutuc[i].name">
                                <input class="form-control text-box single-line" data-val="true" data-val-length="The field name must be a string with a maximum length of 255." data-val-length-max="255" id="@ViewBag.thongtinthutuc" name="@ViewBag.thongtinthutuc" type="text" value="" />
                                <span class="field-validation-valid text-danger" data-valmsg-for="name" data-valmsg-replace="true"></span>
                            </div>
                        </div>
                    }
                }

                <div class="form-group">
                    <label class="control-label col-md-2" for="anh">File</label>
                    <div class="col-md-10">
                        <input type="file" name="file" id="file" /><br><br>
                    </div>
                </div>




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>

            </div>
        }
    </body>

DichVuMotCua/Views/thutucs/DSCapInTheSinhVien.cshtml
@model DichVuMotCua.Models.loaithutuc
@{
    ViewBag.Title = "DSCapGiayChungNhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <body>
        <h2>Danh Sách Cấp In Thẻ Sinh Viên</h2>

        <table class="table">
            <tr>
                <th>
                    id
                </th>
                <th>
                    Tên Thủ Tục
                </th>
                @foreach (var item in ViewBag.loaithutuc)
                {
                    <th>
                        @item.name
                    </th>
                }
                <th>
                    Thao Tác
                </th>

            </tr>
            @{
                var isCheck = false;
            }
            @foreach (var item in ViewBag.thutuc)
            {
                <tr>
                    <td>
                        @item.id
                    </td>
                    <td>
                        @item.name
                    </td>

                    @for (int i = 0; i < ViewBag.loaithutuc.Count; i++)
                    {
                        isCheck = false;
                        foreach (var chitietthutuc in ViewBag.chitietthutuc)
                        {
                            if (chitietthutuc.noidung == ViewBag.loaithutuc[i].name && chitietthutuc.thutuc == item.id)
                            {
                                <td>
                                    @chitietthutuc.value
                                </td>
                                isCheck = true;
                            }


                        }
                        if (!isCheck)
                        {
                            <td>
                                NULL
                            </td>
                        }

                    }

                    <td>

                        @Html.ActionLink("Delete", "Delete", new { id = item.id })
                    </td>
                </tr>
            }

        </table>
    </body>

DichVuMotCua/Views/thutucs/DSCapNhatThongTin.cshtml
@model DichVuMotCua.Models.loaithutuc
@{
    ViewBag.Title = "DSCapGiayChungNhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <h2>Danh Sách Cập Nhật Thông Tin</h2>
    <table class="table">
        <tr>
            <th>
                id
            </th>
            <th>
                Tên Thủ Tục
            </th>
            @foreach (var item in ViewBag.loaithutuc)
            {
                <th>
                    @item.name
                </th>
            }
            <th>
                Thao Tác
            </th>

        </tr>
        @{
            var isCheck = false;
        }
        @foreach (var item in ViewBag.thutuc)
        {
            <tr>
                <td>
                    @item.id
                </td>
                <td>
                    @item.name
                </td>

                @for (int i = 0; i < ViewBag.loaithutuc.Count; i++)
                {
                    isCheck = false;
                    foreach (var chitietthutuc in ViewBag.chitietthutuc)
                    {
                        if (chitietthutuc.noidung == ViewBag.loaithutuc[i].name && chitietthutuc.thutuc == item.id)
                        {
                            <td>
                                @chitietthutuc.value
                            </td>
                            isCheck = true;
                        }


                    }
                    if (!isCheck)
                    {
                        <td>
                            NULL
                        </td>
                    }

                }

                <td>

                    @Html.ActionLink("Delete", "Delete", new { id = item.id })/
                    @if (item.nguoiduyet != null)
                    {
                        if (item.ngaylay == null)
                        {
                            <!--Modal: Login with Avatar Form-->
                            <div class="modal fade" id="HenNgayLay-@item.id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog cascading-modal modal-avatar modal-sm" role="document">
                                    <!--Content-->
                                    <div class="modal-content">

                                        <!--Header-->
                                        <div class="modal-header">
                                            <img src="https://previews.123rf.com/images/victor85/victor851711/victor85171100326/90448522-mail-icon-with-long-shadow-flat-design-style-round-icon-mail-silhouette-simple-circle-icon-modern-fl.jpg" alt="avatar" class="rounded-circle img-responsive" width="200">
                                        </div>
                                        <!--Body-->
                                        <div class="modal-body text-center mb-1">


                                            <form action="HenNgayLay/@item.id" method="post">
                                                <input type="date" name="ngaylay" id="ngaylayhs" />
                                                <input type="hidden" name="form" value="DSCapNhatThongTin" />
                                                <input type="submit" value="submit" />

                                            </form>


                                        </div>

                                    </div>
                                    <!--/.Content-->
                                </div>
                            </div>
                            <!--Modal: Login with Avatar Form-->

                            <div class="text-center">
                                <a href="" data-toggle="modal" data-target="#HenNgayLay-@item.id">
                                    Hẹn Ngày Lấy
                                </a>
                            </div>
                        }
                        else if (item.tinhtrang == null)
                        {
                            @Html.ActionLink("Xác Nhận Đã Lấy", "DaLay", new { id = item.id, form = "DSCapNhatThongTin" })
                        }
                        else
                        {
                            <span>Đã Lấy</span>
                        }
                    }
                    else
                    {
                        @Html.ActionLink("Duyệt", "Duyet", new { id = item.id, form = "DSDangKyHocVuot" })
                    }
                </td>
            </tr>
        }

    </table>
</body>

DichVuMotCua/Views/thutucs/DSHocCham.cshtml
@model DichVuMotCua.Models.loaithutuc
@{
    ViewBag.Title = "DS Học Chậm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<body>
    <h2>Danh Sách Học Chậm</h2>
    <table class="table">
        <tr>
            <th>
                id
            </th>
            <th>
                Tên Thủ Tục
            </th>
            @{
                
                int iCount = 0;
            }
            @foreach (var item in ViewBag.loaithutuc)
            {

                <th>
                    @item.name
                </th>
                iCount++;
                if (iCount > 19)
                {
                    break;
                }
            }
            <th>
                Thao Tác
            </th>

        </tr>
        @{
            var isCheck = false;
            
        }
        @foreach (var item in ViewBag.thutuc)
        {
           
            <tr>
                <td>
                    @item.id
                </td>
                <td>
                    @item.name
                </td>

                @for (int i = 0; i < ViewBag.loaithutuc.Count; i++)
                {
                    isCheck = false;
                    foreach (var chitietthutuc in ViewBag.chitietthutuc)
                    {
                        if (chitietthutuc.noidung == ViewBag.loaithutuc[i].name && chitietthutuc.thutuc == item.id)
                        {
                            <td>
                                @chitietthutuc.value
                            </td>
                            isCheck = true;
                        }


                    }
                    if (!isCheck)
                    {
                        <td>
                            NULL
                        </td>
                    }

                    if(i>19)
                    {
                        break;
                    }

                }

            <td>
                @Html.ActionLink("Chi Tiết", "Details", new { id = item.id, idForm = 9 })
                /
                @Html.ActionLink("Xóa", "Delete", new { id = item.id, form = "DSHocCham" })/
                @if (item.nguoiduyet != null)
                {
                    if (item.ngaylay == null)
{
<!--Modal: Login with Avatar Form-->
<div class="modal fade" id="HenNgayLay-@item.id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
 aria-hidden="true">
<div class="modal-dialog cascading-modal modal-avatar modal-sm" role="document">
<!--Content-->
<div class="modal-content">

<!--Header-->
<div class="modal-header">
<img src="https://previews.123rf.com/images/victor85/victor851711/victor85171100326/90448522-mail-icon-with-long-shadow-flat-design-style-round-icon-mail-silhouette-simple-circle-icon-modern-fl.jpg" alt="avatar" class="rounded-circle img-responsive" width="200">
</div>
<!--Body-->
<div class="modal-body text-center mb-1">


<form action="HenNgayLay/@item.id" method="post">
<input type="date" name="ngaylay" id="ngaylayhs" />
<input type="hidden" name="form" value="DSHocCham" />
<input type="submit" value="submit" />

</form>


</div>

</div>
<!--/.Content-->
</div>
</div>
<!--Modal: Login with Avatar Form-->

<div class="text-center">
<a href="" data-toggle="modal" data-target="#HenNgayLay-@item.id">
Hẹn Ngày Lấy
</a>
</div>
}
else if(item.tinhtrang == null)
{
@Html.ActionLink("Xác Nhận Đã Lấy", "DaLay", new { id = item.id, form = "DSHocCham" })
}
else
{
<span>Đã Lấy</span>
}
                }
                else
                {
                    @Html.ActionLink("Duyệt", "Duyet", new { id = item.id, form = "DSHocCham" })
                }
            </td>
            </tr>
        }

    </table>
</body>

DichVuMotCua/Views/thutucs/DSMOTACHUONGTRINHDAOTAO.cshtml
@model DichVuMotCua.Models.loaithutuc
@{
    ViewBag.Title = "DSCapGiayChungNhan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <body>
        <h2>Danh Sách</h2>
        <table class="table">
            <tr>
                <th>
                    id
                </th>
                <th>
                    Tên Thủ Tục
                </th>
				@{

                int iCount = 0;
				}
                @foreach (var item in ViewBag.loaithutuc)
                {
					iCount++;
					if (iCount > 7)
                {
                    break;
                }
                    <th>
                        @item.hienthi
                    </th>
                }
                <th>
                    Thao Tác
                </th>

            </tr>
            @{
                var isCheck = false;
            }
            @foreach (var item in ViewBag.thutuc)
            {
                <tr>
                    <td>
                        @item.id
                    </td>
                    <td>
                        @item.name
                    </td>

                    @for (int i = 0; i < ViewBag.loaithutuc.Count; i++)
                    {
                        isCheck = false;
                        foreach (var chitietthutuc in ViewBag.chitietthutuc)
                        {
                            if (chitietthutuc.noidung == ViewBag.loaithutuc[i].name && chitietthutuc.thutuc == item.id)
                            {
                                <td>
                                    @chitietthutuc.value
                                </td>
                                isCheck = true;
                            }


                        }
                        if (!isCheck)
                        {
                            <td>
                                NULL
                            </td>
                        }
						
						if(i> 5)
                    {
                        break;
                    }

                    }

                <td>
                    @Html.ActionLink("Chi Tiết", "Details", new { id = item.id, idForm = 35 })
                    /
                    @Html.ActionLink("Xóa", "Delete", new { id = item.id, form = "DSMOTACHUONGTRINHDAOTAO" })/
                    @if (item.nguoiduyet != null)
                    {
                        if (item.ngaylay == null)
{
<!--Modal: Login with Avatar Form-->
<div class="modal fade" id="HenNgayLay-@item.id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
 aria-hidden="true">
<div class="modal-dialog cascading-modal modal-avatar modal-sm" role="document">
<!--Content-->
<div class="modal-content">

<!--Header-->
<div class="modal-header">
<img src="https://previews.123rf.com/images/victor85/victor851711/victor85171100326/90448522-mail-icon-with-long-shadow-flat-design-style-round-icon-mail-silhouette-simple-circle-icon-modern-fl.jpg" alt="avatar" class="rounded-circle img-responsive" width="200">
</div>
<!--Body-->
<div class="modal-body text-center mb-1">


<form action="HenNgayLay/@item.id" method="post">
<input type="date" name="ngaylay" id="ngaylayhs" />
<input type="hidden" name="form" value="DSMOTACHUONGTRINHDAOTAO" />
<input type="submit" value="submit" />

</form>


</div>

</div>
<!--/.Content-->
</div>
</div>
<!--Modal: Login with Avatar Form-->

<div class="text-center">
<a href="" data-toggle="modal" data-target="#HenNgayLay-@item.id">
Hẹn Ngày Lấy
</a>
</div>
}
else if(item.tinhtrang == null)
{
@Html.ActionLink("Xác Nhận Đã Lấy", "DaLay", new { id = item.id, form = "DSMOTACHUONGTRINHDAOTAO" })
}
else
{
<span>Đã Lấy</span>
}
                    }
                    else
                    {
                        @Html.ActionLink("Duyệt", "Duyet", new { id = item.id, form = "DSMOTACHUONGTRINHDAOTAO" })
                    }/
                    @if (item.ghichu != null && item.nguoiduyet == null)
                    {
                        <button type="button"  data-toggle="modal" data-target="#myModal">
                           xem nội dung
                        </button>

                        <!-- The Modal -->
                        <div class="modal" id="myModal">
                            <div class="modal-dialog">
                                <div class="modal-content">

                                    <!-- Modal Header -->
                                    <div class="modal-header">
                                        <h4 class="modal-title">Nội Dung Yêu Cầu</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>

                                    <!-- Modal body -->
                                    <div class="modal-body">
                                        @(item.ghichu)
                                    </div>

                                    <!-- Modal footer -->
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    }
                    else if(item.nguoiduyet == null)
                    {
                        <!--Modal: Login with Avatar Form-->
                        <div class="modal fade" id="modalLoginAvatar-@item.id" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                             aria-hidden="true">
                            <div class="modal-dialog cascading-modal modal-avatar modal-sm" role="document">
                                <!--Content-->
                                <div class="modal-content">

                                    <!--Header-->
                                    <div class="modal-header">
                                        <img src="https://previews.123rf.com/images/victor85/victor851711/victor85171100326/90448522-mail-icon-with-long-shadow-flat-design-style-round-icon-mail-silhouette-simple-circle-icon-modern-fl.jpg" alt="avatar" class="rounded-circle img-responsive" width = "200">
                                    </div>
                                    <!--Body-->
                                    <div class="modal-body text-center mb-1">


                                        <form action="YeuCauSua/@item.id" method="post">
                                            <input type="text" name="noidung" />
                                            <input type="hidden" name="form" value="DSMOTACHUONGTRINHDAOTAO" />
                                            <input type="submit" value="submit" />

                                        </form>


                                    </div>

                                </div>
                                <!--/.Content-->
                            </div>
                        </div>
                        <!--Modal: Login with Avatar Form-->

                        <div class="text-center">
                            <a href="" data-toggle="modal" data-target="#modalLoginAvatar-@item.id">
                                yêu cầu sửa
                            </a>
                        </div>
                    }

                </td>
                </tr>
            }

        </table>
    </body>

DichVuMotCua/Views/thutucs/Details.cshtml
@model DichVuMotCua.Models.thutuc

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}